import { Archivo } from 'next/font/google'
import './globals.css'
import { ThemeProvider } from '../components/partials/providers'
import Header from '@/components/partials/Header'
import { Suspense } from 'react'
import Loading from './loading'
import SmoothScrolling from '@/components/SmoothScrolling'
import Footer from '@/components/partials/Footer'

const archivo = Archivo({ subsets: ['latin'] })

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app'
}

export default function RootLayout({ children }) {
    return (
        <html lang='en' suppressHydrationWarning>
            <body className={archivo.className}>
                <ThemeProvider
                    attribute='class'
                    defaultTheme='system'
                    enableSystem
                    disableTransitionOnChange
                >
                    <Header />
                    <Suspense fallback={<Loading />}>
                        <SmoothScrolling>{children}</SmoothScrolling>
                    </Suspense>
                    <Footer />
                </ThemeProvider>
            </body>
        </html>
    )
}
