import { Open_Sans as FontSans } from 'next/font/google'
// import { Archivo as FontSans } from 'next/font/google'
import './globals.css'
import { ThemeProvider } from '../components/partials/providers'
import Header from '@/components/partials/Header'
import { Suspense } from 'react'
import Loading from './loading'
import SmoothScrolling from '@/components/SmoothScrolling'
import Footer from '@/components/partials/Footer'
import { cn } from '@/lib/utils'

export const fontSans = FontSans({
    subsets: ['latin'],
    variable: '--font-sans'
})

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app'
}

export default function RootLayout({ children }) {
    return (
        <html lang='en' suppressHydrationWarning>
            <body
                className={cn(
                    'min-h-screen bg-backgroundColor font-sans antialiased dark:bg-backgroundColorDark',
                    fontSans.variable
                )}
            >
                <ThemeProvider
                    attribute='class'
                    defaultTheme='system'
                    enableSystem
                    disableTransitionOnChange
                >
                    <Header />
                    <Suspense fallback={<Loading />}>
                        <SmoothScrolling>{children}</SmoothScrolling>
                    </Suspense>
                    <Footer />
                </ThemeProvider>
            </body>
        </html>
    )
}
